### PR TITLE
End-to-end running notebook v0

### PR DESCRIPTION
**Pull request by aittalam**

### CODE REVIEW

**Review by veekaybee — APPROVED** [review]
Notebook looks good based on previous discussion!

**Comment by chainlink** [comment]
I think we need to add pandas to requirements.txt?

**Comment by aittalam** [comment]
> I think we need to add pandas to requirements.txt?

Have you had a chance to `pip install requirements.txt`? I am quite sure `pandas` is installed automatically with datasets and the reason the notebook broke when importing it is that requirements were not automatically installed before user login.
I'll try to replicate this on a fresh notebook install and add pandas if it is missing, thanks!

image

**Comment by aittalam** [comment]
> > I think we need to add pandas to requirements.txt?
> 
> Have you had a chance to `%pip install -r requirements.txt`? I am quite sure `pandas` is installed automatically with datasets and the reason the notebook broke when importing it is that requirements were not automatically installed before user login. I'll try to replicate this on a fresh notebook install and add pandas if it is missing, thanks!

Tested, we are good!

image

**Pull request merged**
